#!/usr/bin/env bash
# Install nginx and returns string "Hello World!" via a GET request
# (requesting a page) using curl

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
server_block=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/ permanent;
        }
}"

bash -c "echo -e '$server_block' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
