#!/usr/bin/env bash
# Install nginx and returns string "Hello World!" via a GET request
# (requesting a page) using curl

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/;\n\t}\n' /etc/nginx/sites-available/default
systemctl restart nginx
