#!/usr/bin/env bash
# Install nginx on the server
# returns string "Hello World!" upon performing a GET request
# to localhost. Implement a 301 permanent redirect to localhost/redirect_me
# return an HTTP 404 error code plus a string Ceci n'est pas une page upon
# requesting an invalid url like localhost/xyz

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
systemctl restart nginx
