#!/usr/bin/env bash
# Install nginx on this server and returns string "Hello World!" via a GET request
# to this server.
# return a custom error message if invalid resource is requested from this server
# Implement a 301 redirect on localhost/redirect_me
# Add response header X-Served-By with value of this server's hostname

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/quduss permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
