#!/usr/bin/env bash
# Install nginx on this server and returns string "Hello World!" via a GET request
# to this server.
# return a custom error message if invalid resource is requested from this server
# Implement a 301 redirect on localhost/redirect_me
# Add response header X-Served-By with value of this server's hostname

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com;\n\t}\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}\n\tadd_header X-Served-By \"$HOSTNAME\";\n/" /etc/nginx/sites-available/default
service nginx restart
