#!/usr/bin/env bash
# Install haproxy on the new ubuntu it is ran on
# serves as a load balancer that uses round robin to distribute requests
# to servers web1 and web2

apt-get install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*
echo -e "\n\nfrontend http\n\tbind *:80\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 100.24.244.250:80 check\n\tserver web2 54.161.241.33:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
