#!/usr/bin/env bash
# generates a MySQL dump that contains all my databases
# and creates a compressed archive out of it

# Define variables
PASSWORD="$1"
DATE=$(date +"%d-%m-%Y")
DUMP_FILE="backup.sql"
ARCHIVE_NAME="$DATE.tar.gz"

# Generate MySQL dump
sudo mysqldump -u root -p"$PASSWORD" --all-databases > "$DUMP_FILE"

# Check if the dump was successful
if [ $? -ne 0 ]; then
    exit 1
fi

# Create compressed archive
tar -czvf "$ARCHIVE_NAME" "$DUMP_FILE"
