#!/usr/bin/env bash
# Print bad luck, good luck, Best School in 4th, 8th and other iterations respectively
i=1
while [ $i -le 10 ];
do
    if [ $i == 4 ]
    then
        echo bad luck
    elif [ $i == 8 ]
    then
        echo good luck
    else
        echo Best School
    fi
    ((i++))
done
