#!/usr/bin/env bash
# Runs nginx web server as the nginx user listening on port 8080.
service nginx start
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
service apache2 stop
service nginx restart
